### ISSUE TITLE
constructr-cassandra not found 

### ISSUE THREAD

**Issue by Belio** [hseeberger/constructr#106]
Adding 
resolvers += Resolver.bintrayRepo("hseeberger", "maven")

libraryDependencies ++= Vector(
  "de.heikoseeberger" %% "constructr-cassandra" % "0.13.2",
  ...
)

 in my build.sbt result in an unresolved dependency. 	

Note: Unresolved dependencies path:
[warn] 		de.heikoseeberger:constructr-cassandra_2.11:0.13.2 (/Users/elio/progetti/iptm/build.sbt#L29-70)
[warn] 		  +- eu.sia.innhub:iptm_2.11:1.0
sbt.ResolveException: unresolved dependency: de.heikoseeberger#constructr-cassandra_2.11;0.13.2: not found

The library seems not to be present on bintray (http://dl.bintray.com/hseeberger/maven/de/heikoseeberger/)

**Comment by hseeberger** [comment]
Thanks for reporting. For some reason the build was configured such that constructr-cassandra doesn't get published. I have changed that and published version 0.13.2-1-g29544ac to Bintray. Starting from the next release all artifacts including constructr-cassandra will be published to Maven Central.
