### ISSUE TITLE
ZK

### ISSUE THREAD

**Issue by ddispaltro** [hseeberger/constructr#116]
Any plans to add support for zookeeper?

Nice project!

**Comment by markusjura** [comment]
Lightbend already implemented a coordination service based on Zookeeper which we currently use internally in the ConductR beta release. Once we are finished with testing, we will release the Zookeeper coordination service as a community plugin, similar to the already existing community plugins: https://github.com/hseeberger/constructr#community-coordination-implementations

**Comment by markusjura** [comment]
The community plugin [constructr-zookeeper](https://github.com/typesafehub/constructr-zookeeper) is ready for use. The current version is `0.1.1` and published to Maven central.

We've battle tested this library in [ConductR](http://conductr.lightbend.com/) under DC/OS.

@hseeberger Can you close this issue?

**Comment by ktoso** [comment]
Hooray!
