### ISSUE TITLE
Setting etcd-port via environment

### ISSUE THREAD

**Issue by ostronom** [hseeberger/constructr#132]
According to https://github.com/hseeberger/constructr/blob/db0f6297b19abd48e1bf6da148c1bfd0980f3b47/constructr-coordination-etcd/src/main/scala/de/heikoseeberger/constructr/coordination/etcd/EtcdCoordination.scala#L65

the port value in config should be a number, but if you are setting it via $"{?ENV_VAR_NAME}" pattern, it comes as a string. Maybe,
```.scala
    val port = system.settings.config.getString("constructr.coordination.port").toInt
``` 

will help?

**Comment by ostronom** [comment]
There was a problem with our build server configuration. I am very sorry about this.

**Comment by hseeberger** [comment]
No worries ;-)
