### ISSUE TITLE
Publish 0.16.0 to maven central

### ISSUE THREAD

**Issue by markusjura** [hseeberger/constructr#147]
ConstructR version 0.16.0 is not part of Maven Central yet.

@hseeberger Did you forgot to publish it to Maven Central? In the README it says:

> All releases including intermediate ones are published here (on Bintray), final ones are also published to Maven Central.

I'd consider the version 0.16.0 as a final version. Or what is your definition of final?

**Comment by hseeberger** [comment]
I have published 0.16.1.

**Comment by markusjura** [comment]
Ok, then the README was misleading because it was still mentioning the version `0.16.0`. Here is a PR to update the README: https://github.com/hseeberger/constructr/pull/148
