### ISSUE TITLE
Java API 

### ISSUE THREAD

**Issue by suyambuganesh** [hseeberger/constructr#149]
Hi,

I would like to experiment with this library in java. So is there a Java api available? or any examples in Java would be very helpful.

Thank you

**Comment by hseeberger** [comment]
Actually ConstructR doesn't have an API at all. You configure it as an extension in `application.conf` and it does its job.

**Comment by suyambuganesh** [comment]
For e.g I wanted to implement an coordination backend in Java .As far as I know, it is not possible to implement the trait Coordination directly in Java. So my question is that whether it is possible for you to expose an Java API?

**Comment by hseeberger** [comment]
I see. No, unfortunately I won't expose a Java API. Sorry.
