### ISSUE TITLE
Fixed path of cluster nodes in EtcdCoordination

### ISSUE THREAD

**Issue by matsluni** [hseeberger/constructr#154]
Hi Heiko,

currently the path for the cluster and the nodes is fixed, see:
[private val baseUri = kvUri.withPath(kvUri.path / "constructr" / clusterName)
](https://github.com/hseeberger/constructr/blob/master/coordination-etcd/src/main/scala/de/heikoseeberger/constructr/coordination/etcd/EtcdCoordination.scala#L71).

Do you think a configurable/custom path would be useful addition?

BR,
Matthias

**Comment by hseeberger** [comment]
Thanks, but not at this moment ... I'm planning for some breaking changes anyway including etcd3 support where there's no more HTTP API.

**Comment by matsluni** [comment]
Ok, look forward to your changes. One question on the etcd3 changes: 
Isn't there some (fixed) path where you need to store the information where to find the nodes for each cluster?

**Comment by hseeberger** [comment]
etcd3 has no REST API but uses gRCP instead. The key space is a flat binary one.
