### ISSUE TITLE
Release for 2.12

### ISSUE THREAD

**Issue by lmlynik** [hseeberger/constructr#164]
I see on Master its already ready.
Contructr is last the dependency which block my code to move to Scala 2.12.

Thanks

**Comment by hseeberger** [comment]
ConstructR has been cross published against 2.11 and 2.12 for quite a while (since 0.15). Of course the latest release is also published against 2.12.

See https://search.maven.org/#artifactdetails%7Cde.heikoseeberger%7Cconstructr_2.12%7C0.17.0%7Cjar
