### ISSUE TITLE
Handle MemberRemoved

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/constructr#24]
In the case of a graceful removal of a member node, ConstructR needs to either remove the respective entry from KV or shutdown the system. I think I prefer the latter, because a system using ConstructR is intended as a cluster member, right?

**Comment by juanjovazquez** [comment]
I totally agree. The situation where a ConstructR node is up but it has been removed from the cluster at the same time would be conflicting or at least inconsistent. Just my two cents. IMHO, the other behaviour could hide a bigger issue in the underlying architecture.

**Comment by raboof** [comment]
Perhaps we should remove the key as soon as `MemberLeft`/`MemberExited`?

Should any node try to remove the entry, or just the node that is leaving?

**Comment by hseeberger** [comment]
In states `MemberLeft` and `MemberExited` the nodes theoretically should still work as seed nodes, hence I think `MemberRemoved` is the right time.

The other thing might be interesting, though. I don't think it's very important, because (a) there's a TTL on the KV entries and (b) we usually use a couple of seed nodes for joining. You could open a ticket, but currently I'm reluctant on adding stuff / making things more complicated. We need tests first.
