### ISSUE TITLE
Isolated mode

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#43]
I have an application that is intended to run clustered, but e.g. for local development it might be convenient to be able to run a single, isolated instance without connecting etcd/consul.

What would be a convenient way to achieve that? Perhaps we could introduce a 'dummy' coordination backend and I could introduce an option to select that one in my application?

**Comment by hseeberger** [comment]
ConstructR already supports that: If you define seed nodes (`akka.cluster.seed-nodes`), then it won't create and use the `ConstructRMachine`. Should work out of the box. Please try and let me know if you have issues.

**Comment by raboof** [comment]
That works - perhaps a bit less 'direct' but a suitable solution.
