### ISSUE TITLE
unhandled event MemberUp(Member(address = ...., status = Up)) in state AddingSelf

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#51]
When starting multiple nodes at the same time I sometimes see this.

**Comment by hseeberger** [comment]
Unregistering from the member service seems to work asynchronously and sometimes too late, so we're getting member events in a state when we aren't interested any more. But that's not at all an issue.

**Comment by raboof** [comment]
Agreed - however currently it is logged at WARN level (sorry I see I didn't mention that in the issue). 

Might be good to explicitly ignore those messages, suppressing the warning.

**Comment by hseeberger** [comment]
I know that FSM logs unhandled events at WARN ;-)

There's no way to ignore those messages, because `ConstructrMachine` doesn't know them. Take a look at the sources and you will see.

**Comment by raboof** [comment]
Well, for example https://github.com/raboof/constructr/commit/12f5a0af2e0f9c548a31a58ab066c2c99ac9cbad would work, but perhaps you don't want to add that dependency on akka-cluster there?

**Comment by hseeberger** [comment]
Exactly. constructr-machine is unaware of akka-cluster and must remain so, because it's also used for Cassandra and maybe others in the future.
