### ISSUE TITLE
Make TTL-factor rules consistent

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#64]
The README (and reference.conf) mention:

```
ttl-factor // Must be greater than 1 + (coordination-timeout * (1 + coordination-retries) / refresh-interval)!
```

However, ConstructrMachineSettings checks:
```
require(
      ttlFactor > 1 + coordinationTimeout / refreshInterval,
      s"ttl-factor must be greater than one plus coordination-timeout divided by refresh-interval, but was $ttlFactor!"
    )
```

In other words: the automated check does not take into account the allowed number of coordination retries.

Do we want to make those consistent?

**Comment by hseeberger** [comment]
Good catch! The precondition is unnecessarily (?) checked twice and no longer consistent with what's going on.

**Comment by hseeberger** [comment]
See #65.
