### ISSUE TITLE
Improve error message when adding self to consul fails

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#65]
`putKeyWithSession` returns `Success(false)` when the PUT call to consul returnes status code 200, and indicates (the body of the response) that the update has not taken place (https://consul.io/docs/agent/http/kv.html)).

In that case, the `if result` in `ConsulCoordination.addSelf` will cause the result to be a `Failure(_)` with the generic error message `java.util.NoSuchElementException: Future.filter predicate is not satisfied`, and no obvious clue in the stacktrace either.

**Comment by hseeberger** [comment]
No longer relevant for this repo.
