### ISSUE TITLE
Investigate using Circe instead of spray-json

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/constructr#69]

**Comment by hseeberger** [comment]
This includes looking at Rapture support for Circe which seems to be available in version 2.

**Comment by ctataryn** [comment]
FYI Looks like Circe now has a bridge for Spray:

https://github.com/travisbrown/circe/releases/tag/v0.4.0

**Comment by hseeberger** [comment]
@ctataryn, as far as I can tell Circe supports JSON marshalling for spray the HTTP library – not to be confused with spray-json. That's not interesting for this project which uses Akka HTTP.

**Comment by ctataryn** [comment]
@hseeberger Ahh I see, sorry! I arrived here after a google search for circe + spray somehow, saw your name and just assumed this was spray related :)
