### ISSUE TITLE
Distinguish between permanent and retryable failures in refreshing

### ISSUE THREAD

**Issue by jaapterwoerds** [hseeberger/constructr#92]
In some case the refresh fails with a permanent error. Instead of going in the retry logic, we could directly stop the ConstructrMachine FSM.

As an example: in the consul-coordinator implementation renewing the session can fail with an unrecoverable error in which retrying is useless. See also: https://github.com/Tecsisa/constructr-consul/issues/5.

**Comment by hseeberger** [comment]
There should be a retry limit. Could you please confirm that this doesn't work during refreshing?

**Comment by jaapterwoerds** [comment]
The retry limit is in place and works as expected.

**Comment by hseeberger** [comment]
Thanks for checking. I can close this then.

**Comment by raboof** [comment]
@hseeberger while indeed the retry limit works, it would be nice to 'fail fast' instead of retrying in case of known-to-be-unrecoverable errors.

**Comment by jaapterwoerds** [comment]
@hseeberger @raboof The intent of this issue was indeed to be able to signal to 'fail fast' from the coordinator implementations.

**Comment by hseeberger** [comment]
The workings of the state machine are already very complex. Adding various ways of failure would increase complexity, hence I'm a bit on the fence here.

Could you please suggest a complete (not only Consul) specification of unrecoverable errors and ways to test the new behavior?
