### ISSUE TITLE
Outgoing Connection 'caches' the IP in Coordination

### ISSUE THREAD

**Issue by juanjovazquez** [hseeberger/constructr#93]
In `Constructr.scala` the `Connection` is initialized and the solved IPs are cached but it's using the same one in every flow materialization. As a result, if that Consul node got down, ConstructR won't try with another IP. 

```scala
val connection = Http()(context.system).outgoingConnection(host, port)
Coordination("akka", context.system.name, context.system.settings.config)
            (connection, ActorMaterializer())
```

This behaviour might be observed during DNS resolution of coordination cluster nodes.

Possible related info:

https://github.com/akka/akka/issues/19419
https://gitter.im/akka/akka?at=569552acee13050b38a32091

**Comment by hseeberger** [comment]
Just to be sure: the caching happens because of `InetSocketAddress` used internally by Akka HTTP resolving the DNS name, right? So possible solution might be to (a) create (not only materialize) the connection every time we send a request or (b) use `HttpExt.singleRequest`.

**Comment by juanjovazquez** [comment]
That's right. I think both solutions might work ;).
