### ISSUE TITLE
More control over what happens when coordination fails

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#95]
The README still mentions: _If something goes wrong, e.g. a timeout (after configurable retries are exhausted) when interacting with the coordination service, ConstructR by default terminates its ActorSystem. At least for constructr-akka this can be changed by providing a custom SupervisorStrategy to the manually started Constructr actor, but be sure you know what you are doing._

The latter is no longer the case, right? `de.heikoseeberger.constructr.akka.Constructr` is final, fixes its SupervisionStrategy to `SupervisorStrategy.stoppingStrategy` and terminates its `ActorSystem` when coordination terminates.

I'd like to have some more control over what to do when coordination fails.

**Comment by hseeberger** [comment]
Currently I don't want to offer more control, because that would make things more complicated. The README has been updated in https://github.com/hseeberger/constructr/commit/46fb9a137127809569c179581ca40570a66413f2.
