### ISSUE TITLE
The party creating the Coordination instance should pass in a LoggingAdapter

### ISSUE THREAD

**Issue by juanjovazquez** [hseeberger/constructr#96]
It would be nice to have access to the Akka `logger` in every particular coordination implementation.

See https://github.com/Tecsisa/constructr-consul/issues/9

**Comment by hseeberger** [comment]
Can't you call `FlowOps.log` in your connection handling flow?

**Comment by raboof** [comment]
Yes, but `FlowOps.log` will log to the `akka.stream.Materializer` logger unless you (implicitly or explicitly) pass it another `LoggingAdapter`.

AFAICS the only way to make a `LoggingAdapter` is by having access to the `ActorSystem`, which coordinators don't, but I could have missed something. Have I?

**Comment by hseeberger** [comment]
You are right and therefore the party creating the `Coordination` instance should pass in a specific `LoggingAdapter` which currently is not the case. If this works for you please rename the issue accordingly.

**Comment by hseeberger** [comment]
Obsolete by #101, because now you have a full `ActorSystem` at your hands.

**Comment by juanjovazquez** [comment]
Nice!
